INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('John', 'Doe', '123 Main St', 'Toronto', 'ON', 'M5V 2S9', '555-1234', 'john.doe@example.com');

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('Jane', 'Smith', '456 Elm St', 'Vancouver', 'BC', 'V6B 2W8', '555-5678', 'jane.smith@example.com');

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('Michael', 'Johnson', '789 Oak St', 'Calgary', 'AB', 'T2P 3C6', '555-9012', 'michael.johnson@example.com');

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('Sarah', 'Wilson', '321 Pine St', 'Montreal', 'QC', 'H2Y 1V7', '555-3456', 'sarah.wilson@example.com');

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('David', 'Anderson', '654 Birch St', 'Halifax', 'NS', 'B3J 1G9', '555-7890', 'david.anderson@example.com');

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, PROVINCE, POSTAL_CODE, PHONE_NUMBER, EMAIL) 
VALUES ('Emily', 'Taylor', '987 Maple St', 'Winnipeg', 'MB', 'R3C 1V8', '555-2345', 'emily.taylor@example.com');
